### ISSUE TITLE
Is the mesh virtual service duplicate when knative-local-gateway is used?

### ISSUE THREAD

**Issue by emaildanwilson** [knative-extensions/net-istio#1123]
We're seeing a ton of unnecessary envoy configuration on each of our gateways (clusters and endpoints mostly) and the source of this is from Knative virtual services which use a gateway of "mesh". This causes Istio to share them with ALL gateways in the mesh. It would be great if the Istio configuration was restricted to only the gateways configured in the config-istio configmap.

Is this duplicate now and should be removed or is it required for some reason?

Thank you!

**Comment by emaildanwilson** [comment]
Maybe it could be set to the configured local gateway instead of `mesh` when one is provided?

**Comment by dprotaso** [comment]
We had a knob before but it was removed cc @nak3 who removed it in https://github.com/knative-sandbox/net-istio/pull/915

How would you configure this property?

**Comment by nak3** [comment]
> Is this duplicate now and should be removed or is it required for some reason?

As you might know, the `mesh` virtual service is used when your ksvc app has side-car injection. It has one advantage that it skips one extra hop which is a istio local gateway. 
I didn't remove the virtualservice in https://github.com/knative/serving/issues/11523 because the virtualservice was used/created regardless of the `local-gateway.mesh: "mesh"`. (In other words, that's the reason why we deprecated the option as commented on [1].)

> Maybe it could be set to the configured local gateway instead of mesh when one is provided?

Yes, if you don't need the mesh virtualservice I think it would be okay to introduce a new configuration.

[1] #11523
> mesh to mesh traffic has no difference between w/ and w/o local-gateway.mesh. The option is just to use only mesh and completely remove local gateway.
